version: '3'

services:
  postgres:
    image: postgres:15.3
    container_name: rauru-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - rauru-postgres:/data/postgres
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rauru-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  rauru-postgres:
