version: '3'

services:
  postgres:
    image: postgres:15.3
    container_name: rauru-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - rauru-postgres:/data/postgres
    ports:
      - '5430:5432'

volumes:
  rauru-postgres:
